#!/bin/bash
PROJECT=$1

if [ "$PROJECT" = "Chart" ]; then
	./extract_projects.sh Chart 1 ./Projects
	./extract_projects.sh Chart 2 ./Projects
	./extract_projects.sh Chart 3 ./Projects
	./extract_projects.sh Chart 4 ./Projects
	./extract_projects.sh Chart 5 ./Projects
	./extract_projects.sh Chart 6 ./Projects
	./extract_projects.sh Chart 7 ./Projects
	./extract_projects.sh Chart 8 ./Projects
	./extract_projects.sh Chart 9 ./Projects
	./extract_projects.sh Chart 10 ./Projects
	./extract_projects.sh Chart 11 ./Projects
	./extract_projects.sh Chart 12 ./Projects
	./extract_projects.sh Chart 13 ./Projects
	./extract_projects.sh Chart 14 ./Projects
	./extract_projects.sh Chart 15 ./Projects
	./extract_projects.sh Chart 16 ./Projects
	./extract_projects.sh Chart 17 ./Projects
	./extract_projects.sh Chart 18 ./Projects
	./extract_projects.sh Chart 19 ./Projects
	./extract_projects.sh Chart 20 ./Projects
	./extract_projects.sh Chart 21 ./Projects
	./extract_projects.sh Chart 22 ./Projects
	./extract_projects.sh Chart 23 ./Projects
	./extract_projects.sh Chart 24 ./Projects
	./extract_projects.sh Chart 25 ./Projects
	./extract_projects.sh Chart 26 ./Projects
fi
if [ "$PROJECT" = "Codec" ]; then
	./extract_projects.sh Codec 1 ./Projects
	./extract_projects.sh Codec 2 ./Projects
	./extract_projects.sh Codec 3 ./Projects
	./extract_projects.sh Codec 4 ./Projects
	./extract_projects.sh Codec 5 ./Projects
	./extract_projects.sh Codec 6 ./Projects
	./extract_projects.sh Codec 7 ./Projects
	./extract_projects.sh Codec 8 ./Projects
	./extract_projects.sh Codec 9 ./Projects
	./extract_projects.sh Codec 10 ./Projects
	./extract_projects.sh Codec 11 ./Projects
	./extract_projects.sh Codec 12 ./Projects
	./extract_projects.sh Codec 13 ./Projects
	./extract_projects.sh Codec 14 ./Projects
	./extract_projects.sh Codec 15 ./Projects
	./extract_projects.sh Codec 16 ./Projects
	./extract_projects.sh Codec 17 ./Projects
	./extract_projects.sh Codec 18 ./Projects
fi
if [ "$PROJECT" = "Collections" ]; then
	./extract_projects.sh Collections 25 ./Projects
	./extract_projects.sh Collections 26 ./Projects
	./extract_projects.sh Collections 27 ./Projects
	./extract_projects.sh Collections 28 ./Projects
fi
if [ "$PROJECT" = "Compress" ]; then
	./extract_projects.sh Compress 1 ./Projects
	./extract_projects.sh Compress 2 ./Projects
	./extract_projects.sh Compress 3 ./Projects
	./extract_projects.sh Compress 4 ./Projects
	./extract_projects.sh Compress 5 ./Projects
	./extract_projects.sh Compress 6 ./Projects
	./extract_projects.sh Compress 7 ./Projects
	./extract_projects.sh Compress 8 ./Projects
	./extract_projects.sh Compress 9 ./Projects
	./extract_projects.sh Compress 10 ./Projects
	./extract_projects.sh Compress 11 ./Projects
	./extract_projects.sh Compress 12 ./Projects
	./extract_projects.sh Compress 13 ./Projects
	./extract_projects.sh Compress 14 ./Projects
	./extract_projects.sh Compress 15 ./Projects
	./extract_projects.sh Compress 16 ./Projects
	./extract_projects.sh Compress 17 ./Projects
	./extract_projects.sh Compress 18 ./Projects
	./extract_projects.sh Compress 19 ./Projects
	./extract_projects.sh Compress 20 ./Projects
	./extract_projects.sh Compress 21 ./Projects
	./extract_projects.sh Compress 22 ./Projects
	./extract_projects.sh Compress 23 ./Projects
	./extract_projects.sh Compress 24 ./Projects
	./extract_projects.sh Compress 25 ./Projects
	./extract_projects.sh Compress 26 ./Projects
	./extract_projects.sh Compress 27 ./Projects
	./extract_projects.sh Compress 28 ./Projects
	./extract_projects.sh Compress 29 ./Projects
	./extract_projects.sh Compress 30 ./Projects
	./extract_projects.sh Compress 31 ./Projects
	./extract_projects.sh Compress 32 ./Projects
	./extract_projects.sh Compress 33 ./Projects
	./extract_projects.sh Compress 34 ./Projects
	./extract_projects.sh Compress 35 ./Projects
	./extract_projects.sh Compress 36 ./Projects
	./extract_projects.sh Compress 37 ./Projects
	./extract_projects.sh Compress 38 ./Projects
	./extract_projects.sh Compress 39 ./Projects
	./extract_projects.sh Compress 40 ./Projects
	./extract_projects.sh Compress 41 ./Projects
	./extract_projects.sh Compress 42 ./Projects
	./extract_projects.sh Compress 43 ./Projects
	./extract_projects.sh Compress 44 ./Projects
	./extract_projects.sh Compress 45 ./Projects
	./extract_projects.sh Compress 46 ./Projects
	./extract_projects.sh Compress 47 ./Projects
fi
if [ "$PROJECT" = "Csv" ]; then
	./extract_projects.sh Csv 1 ./Projects
	./extract_projects.sh Csv 2 ./Projects
	./extract_projects.sh Csv 3 ./Projects
	./extract_projects.sh Csv 4 ./Projects
	./extract_projects.sh Csv 5 ./Projects
	./extract_projects.sh Csv 6 ./Projects
	./extract_projects.sh Csv 7 ./Projects
	./extract_projects.sh Csv 8 ./Projects
	./extract_projects.sh Csv 9 ./Projects
	./extract_projects.sh Csv 10 ./Projects
	./extract_projects.sh Csv 11 ./Projects
	./extract_projects.sh Csv 12 ./Projects
	./extract_projects.sh Csv 13 ./Projects
	./extract_projects.sh Csv 14 ./Projects
	./extract_projects.sh Csv 15 ./Projects
	./extract_projects.sh Csv 16 ./Projects
fi
if [ "$PROJECT" = "Gson" ]; then
	./extract_projects.sh Gson 1 ./Projects
	./extract_projects.sh Gson 2 ./Projects
	./extract_projects.sh Gson 3 ./Projects
	./extract_projects.sh Gson 4 ./Projects
	./extract_projects.sh Gson 5 ./Projects
	./extract_projects.sh Gson 6 ./Projects
	./extract_projects.sh Gson 7 ./Projects
	./extract_projects.sh Gson 8 ./Projects
	./extract_projects.sh Gson 9 ./Projects
	./extract_projects.sh Gson 10 ./Projects
	./extract_projects.sh Gson 11 ./Projects
	./extract_projects.sh Gson 12 ./Projects
	./extract_projects.sh Gson 13 ./Projects
	./extract_projects.sh Gson 14 ./Projects
	./extract_projects.sh Gson 15 ./Projects
	./extract_projects.sh Gson 16 ./Projects
	./extract_projects.sh Gson 17 ./Projects
	./extract_projects.sh Gson 18 ./Projects
fi
if [ "$PROJECT" = "JacksonCore" ]; then
	./extract_projects.sh JacksonCore 1 ./Projects
	./extract_projects.sh JacksonCore 2 ./Projects
	./extract_projects.sh JacksonCore 3 ./Projects
	./extract_projects.sh JacksonCore 4 ./Projects
	./extract_projects.sh JacksonCore 5 ./Projects
	./extract_projects.sh JacksonCore 6 ./Projects
	./extract_projects.sh JacksonCore 7 ./Projects
	./extract_projects.sh JacksonCore 8 ./Projects
	./extract_projects.sh JacksonCore 9 ./Projects
	./extract_projects.sh JacksonCore 10 ./Projects
	./extract_projects.sh JacksonCore 11 ./Projects
	./extract_projects.sh JacksonCore 12 ./Projects
	./extract_projects.sh JacksonCore 13 ./Projects
	./extract_projects.sh JacksonCore 14 ./Projects
	./extract_projects.sh JacksonCore 15 ./Projects
	./extract_projects.sh JacksonCore 16 ./Projects
	./extract_projects.sh JacksonCore 17 ./Projects
	./extract_projects.sh JacksonCore 18 ./Projects
	./extract_projects.sh JacksonCore 19 ./Projects
	./extract_projects.sh JacksonCore 20 ./Projects
	./extract_projects.sh JacksonCore 21 ./Projects
	./extract_projects.sh JacksonCore 22 ./Projects
	./extract_projects.sh JacksonCore 23 ./Projects
	./extract_projects.sh JacksonCore 24 ./Projects
	./extract_projects.sh JacksonCore 25 ./Projects
	./extract_projects.sh JacksonCore 26 ./Projects
fi
if [ "$PROJECT" = "JacksonXml" ]; then
	./extract_projects.sh JacksonXml 1 ./Projects
	./extract_projects.sh JacksonXml 2 ./Projects
	./extract_projects.sh JacksonXml 3 ./Projects
	./extract_projects.sh JacksonXml 4 ./Projects
	./extract_projects.sh JacksonXml 5 ./Projects
	./extract_projects.sh JacksonXml 6 ./Projects
fi
if [ "$PROJECT" = "Jsoup" ]; then
	./extract_projects.sh Jsoup 1 ./Projects
	./extract_projects.sh Jsoup 2 ./Projects
	./extract_projects.sh Jsoup 3 ./Projects
	./extract_projects.sh Jsoup 4 ./Projects
	./extract_projects.sh Jsoup 5 ./Projects
	./extract_projects.sh Jsoup 6 ./Projects
	./extract_projects.sh Jsoup 7 ./Projects
	./extract_projects.sh Jsoup 8 ./Projects
	./extract_projects.sh Jsoup 9 ./Projects
	./extract_projects.sh Jsoup 10 ./Projects
	./extract_projects.sh Jsoup 11 ./Projects
	./extract_projects.sh Jsoup 12 ./Projects
	./extract_projects.sh Jsoup 13 ./Projects
	./extract_projects.sh Jsoup 14 ./Projects
	./extract_projects.sh Jsoup 15 ./Projects
	./extract_projects.sh Jsoup 16 ./Projects
	./extract_projects.sh Jsoup 17 ./Projects
	./extract_projects.sh Jsoup 18 ./Projects
	./extract_projects.sh Jsoup 19 ./Projects
	./extract_projects.sh Jsoup 20 ./Projects
	./extract_projects.sh Jsoup 21 ./Projects
	./extract_projects.sh Jsoup 22 ./Projects
	./extract_projects.sh Jsoup 23 ./Projects
	./extract_projects.sh Jsoup 24 ./Projects
	./extract_projects.sh Jsoup 25 ./Projects
	./extract_projects.sh Jsoup 26 ./Projects
	./extract_projects.sh Jsoup 27 ./Projects
	./extract_projects.sh Jsoup 28 ./Projects
	./extract_projects.sh Jsoup 29 ./Projects
	./extract_projects.sh Jsoup 30 ./Projects
	./extract_projects.sh Jsoup 31 ./Projects
	./extract_projects.sh Jsoup 32 ./Projects
	./extract_projects.sh Jsoup 33 ./Projects
	./extract_projects.sh Jsoup 34 ./Projects
	./extract_projects.sh Jsoup 35 ./Projects
	./extract_projects.sh Jsoup 36 ./Projects
	./extract_projects.sh Jsoup 37 ./Projects
	./extract_projects.sh Jsoup 38 ./Projects
	./extract_projects.sh Jsoup 39 ./Projects
	./extract_projects.sh Jsoup 40 ./Projects
	./extract_projects.sh Jsoup 41 ./Projects
	./extract_projects.sh Jsoup 42 ./Projects
	./extract_projects.sh Jsoup 43 ./Projects
	./extract_projects.sh Jsoup 44 ./Projects
	./extract_projects.sh Jsoup 45 ./Projects
	./extract_projects.sh Jsoup 46 ./Projects
	./extract_projects.sh Jsoup 47 ./Projects
	./extract_projects.sh Jsoup 48 ./Projects
	./extract_projects.sh Jsoup 49 ./Projects
	./extract_projects.sh Jsoup 50 ./Projects
	./extract_projects.sh Jsoup 51 ./Projects
	./extract_projects.sh Jsoup 52 ./Projects
	./extract_projects.sh Jsoup 53 ./Projects
	./extract_projects.sh Jsoup 54 ./Projects
	./extract_projects.sh Jsoup 55 ./Projects
	./extract_projects.sh Jsoup 56 ./Projects
	./extract_projects.sh Jsoup 57 ./Projects
	./extract_projects.sh Jsoup 58 ./Projects
	./extract_projects.sh Jsoup 59 ./Projects
	./extract_projects.sh Jsoup 60 ./Projects
	./extract_projects.sh Jsoup 61 ./Projects
	./extract_projects.sh Jsoup 62 ./Projects
	./extract_projects.sh Jsoup 63 ./Projects
	./extract_projects.sh Jsoup 64 ./Projects
	./extract_projects.sh Jsoup 65 ./Projects
	./extract_projects.sh Jsoup 66 ./Projects
	./extract_projects.sh Jsoup 67 ./Projects
	./extract_projects.sh Jsoup 68 ./Projects
	./extract_projects.sh Jsoup 69 ./Projects
	./extract_projects.sh Jsoup 70 ./Projects
	./extract_projects.sh Jsoup 71 ./Projects
	./extract_projects.sh Jsoup 72 ./Projects
	./extract_projects.sh Jsoup 73 ./Projects
	./extract_projects.sh Jsoup 74 ./Projects
	./extract_projects.sh Jsoup 75 ./Projects
	./extract_projects.sh Jsoup 76 ./Projects
	./extract_projects.sh Jsoup 77 ./Projects
	./extract_projects.sh Jsoup 78 ./Projects
	./extract_projects.sh Jsoup 79 ./Projects
	./extract_projects.sh Jsoup 80 ./Projects
	./extract_projects.sh Jsoup 81 ./Projects
	./extract_projects.sh Jsoup 82 ./Projects
	./extract_projects.sh Jsoup 83 ./Projects
	./extract_projects.sh Jsoup 84 ./Projects
	./extract_projects.sh Jsoup 85 ./Projects
	./extract_projects.sh Jsoup 86 ./Projects
	./extract_projects.sh Jsoup 87 ./Projects
	./extract_projects.sh Jsoup 88 ./Projects
	./extract_projects.sh Jsoup 89 ./Projects
	./extract_projects.sh Jsoup 90 ./Projects
	./extract_projects.sh Jsoup 91 ./Projects
	./extract_projects.sh Jsoup 92 ./Projects
	./extract_projects.sh Jsoup 93 ./Projects
fi
if [ "$PROJECT" = "JxPath" ]; then
	./extract_projects.sh JxPath 1 ./Projects
	./extract_projects.sh JxPath 2 ./Projects
	./extract_projects.sh JxPath 3 ./Projects
	./extract_projects.sh JxPath 4 ./Projects
	./extract_projects.sh JxPath 5 ./Projects
	./extract_projects.sh JxPath 6 ./Projects
	./extract_projects.sh JxPath 7 ./Projects
	./extract_projects.sh JxPath 8 ./Projects
	./extract_projects.sh JxPath 9 ./Projects
	./extract_projects.sh JxPath 10 ./Projects
	./extract_projects.sh JxPath 11 ./Projects
	./extract_projects.sh JxPath 12 ./Projects
	./extract_projects.sh JxPath 13 ./Projects
	./extract_projects.sh JxPath 14 ./Projects
	./extract_projects.sh JxPath 15 ./Projects
	./extract_projects.sh JxPath 16 ./Projects
	./extract_projects.sh JxPath 17 ./Projects
	./extract_projects.sh JxPath 18 ./Projects
	./extract_projects.sh JxPath 19 ./Projects
	./extract_projects.sh JxPath 20 ./Projects
	./extract_projects.sh JxPath 21 ./Projects
	./extract_projects.sh JxPath 22 ./Projects
fi
if [ "$PROJECT" = "Lang" ]; then
	./extract_projects.sh Lang 1 ./Projects
	./extract_projects.sh Lang 3 ./Projects
	./extract_projects.sh Lang 4 ./Projects
	./extract_projects.sh Lang 5 ./Projects
	./extract_projects.sh Lang 6 ./Projects
	./extract_projects.sh Lang 7 ./Projects
	./extract_projects.sh Lang 8 ./Projects
	./extract_projects.sh Lang 9 ./Projects
	./extract_projects.sh Lang 10 ./Projects
	./extract_projects.sh Lang 11 ./Projects
	./extract_projects.sh Lang 12 ./Projects
	./extract_projects.sh Lang 13 ./Projects
	./extract_projects.sh Lang 14 ./Projects
	./extract_projects.sh Lang 15 ./Projects
	./extract_projects.sh Lang 16 ./Projects
	./extract_projects.sh Lang 17 ./Projects
	./extract_projects.sh Lang 18 ./Projects
	./extract_projects.sh Lang 19 ./Projects
	./extract_projects.sh Lang 20 ./Projects
	./extract_projects.sh Lang 21 ./Projects
	./extract_projects.sh Lang 22 ./Projects
	./extract_projects.sh Lang 23 ./Projects
	./extract_projects.sh Lang 24 ./Projects
	./extract_projects.sh Lang 25 ./Projects
	./extract_projects.sh Lang 26 ./Projects
	./extract_projects.sh Lang 27 ./Projects
	./extract_projects.sh Lang 28 ./Projects
	./extract_projects.sh Lang 29 ./Projects
	./extract_projects.sh Lang 30 ./Projects
	./extract_projects.sh Lang 31 ./Projects
	./extract_projects.sh Lang 32 ./Projects
	./extract_projects.sh Lang 33 ./Projects
	./extract_projects.sh Lang 34 ./Projects
	./extract_projects.sh Lang 35 ./Projects
	./extract_projects.sh Lang 36 ./Projects
	./extract_projects.sh Lang 37 ./Projects
	./extract_projects.sh Lang 38 ./Projects
	./extract_projects.sh Lang 39 ./Projects
	./extract_projects.sh Lang 40 ./Projects
	./extract_projects.sh Lang 41 ./Projects
	./extract_projects.sh Lang 42 ./Projects
	./extract_projects.sh Lang 43 ./Projects
	./extract_projects.sh Lang 44 ./Projects
	./extract_projects.sh Lang 45 ./Projects
	./extract_projects.sh Lang 46 ./Projects
	./extract_projects.sh Lang 47 ./Projects
	./extract_projects.sh Lang 48 ./Projects
	./extract_projects.sh Lang 49 ./Projects
	./extract_projects.sh Lang 50 ./Projects
	./extract_projects.sh Lang 51 ./Projects
	./extract_projects.sh Lang 52 ./Projects
	./extract_projects.sh Lang 53 ./Projects
	./extract_projects.sh Lang 54 ./Projects
	./extract_projects.sh Lang 55 ./Projects
	./extract_projects.sh Lang 56 ./Projects
	./extract_projects.sh Lang 57 ./Projects
	./extract_projects.sh Lang 58 ./Projects
	./extract_projects.sh Lang 59 ./Projects
	./extract_projects.sh Lang 60 ./Projects
	./extract_projects.sh Lang 61 ./Projects
	./extract_projects.sh Lang 62 ./Projects
	./extract_projects.sh Lang 63 ./Projects
	./extract_projects.sh Lang 64 ./Projects
	./extract_projects.sh Lang 65 ./Projects
fi
if [ "$PROJECT" = "Mockito" ]; then
	./extract_projects.sh Mockito 1 ./Projects
	./extract_projects.sh Mockito 2 ./Projects
	./extract_projects.sh Mockito 3 ./Projects
	./extract_projects.sh Mockito 4 ./Projects
	./extract_projects.sh Mockito 5 ./Projects
	./extract_projects.sh Mockito 6 ./Projects
	./extract_projects.sh Mockito 7 ./Projects
	./extract_projects.sh Mockito 8 ./Projects
	./extract_projects.sh Mockito 9 ./Projects
	./extract_projects.sh Mockito 10 ./Projects
	./extract_projects.sh Mockito 11 ./Projects
	./extract_projects.sh Mockito 12 ./Projects
	./extract_projects.sh Mockito 13 ./Projects
	./extract_projects.sh Mockito 14 ./Projects
	./extract_projects.sh Mockito 15 ./Projects
	./extract_projects.sh Mockito 16 ./Projects
	./extract_projects.sh Mockito 17 ./Projects
	./extract_projects.sh Mockito 18 ./Projects
	./extract_projects.sh Mockito 19 ./Projects
	./extract_projects.sh Mockito 20 ./Projects
	./extract_projects.sh Mockito 21 ./Projects
	./extract_projects.sh Mockito 22 ./Projects
	./extract_projects.sh Mockito 23 ./Projects
	./extract_projects.sh Mockito 24 ./Projects
	./extract_projects.sh Mockito 25 ./Projects
	./extract_projects.sh Mockito 26 ./Projects
	./extract_projects.sh Mockito 27 ./Projects
	./extract_projects.sh Mockito 28 ./Projects
	./extract_projects.sh Mockito 29 ./Projects
	./extract_projects.sh Mockito 30 ./Projects
	./extract_projects.sh Mockito 31 ./Projects
	./extract_projects.sh Mockito 32 ./Projects
	./extract_projects.sh Mockito 33 ./Projects
	./extract_projects.sh Mockito 34 ./Projects
	./extract_projects.sh Mockito 35 ./Projects
	./extract_projects.sh Mockito 36 ./Projects
	./extract_projects.sh Mockito 37 ./Projects
	./extract_projects.sh Mockito 38 ./Projects
fi
if [ "$PROJECT" = "Time" ]; then
	./extract_projects.sh Time 1 ./Projects
	./extract_projects.sh Time 2 ./Projects
	./extract_projects.sh Time 3 ./Projects
	./extract_projects.sh Time 4 ./Projects
	./extract_projects.sh Time 5 ./Projects
	./extract_projects.sh Time 6 ./Projects
	./extract_projects.sh Time 7 ./Projects
	./extract_projects.sh Time 8 ./Projects
	./extract_projects.sh Time 9 ./Projects
	./extract_projects.sh Time 10 ./Projects
	./extract_projects.sh Time 11 ./Projects
	./extract_projects.sh Time 12 ./Projects
	./extract_projects.sh Time 13 ./Projects
	./extract_projects.sh Time 14 ./Projects
	./extract_projects.sh Time 15 ./Projects
	./extract_projects.sh Time 16 ./Projects
	./extract_projects.sh Time 17 ./Projects
	./extract_projects.sh Time 18 ./Projects
	./extract_projects.sh Time 19 ./Projects
	./extract_projects.sh Time 20 ./Projects
	./extract_projects.sh Time 22 ./Projects
	./extract_projects.sh Time 23 ./Projects
	./extract_projects.sh Time 24 ./Projects
	./extract_projects.sh Time 25 ./Projects
	./extract_projects.sh Time 26 ./Projects
	./extract_projects.sh Time 27 ./Projects
fi
if [ "$PROJECT" = "Cli" ]; then
	./extract_projects.sh Cli 1 ./Projects
	./extract_projects.sh Cli 2 ./Projects
	./extract_projects.sh Cli 3 ./Projects
	./extract_projects.sh Cli 4 ./Projects
	./extract_projects.sh Cli 5 ./Projects
	./extract_projects.sh Cli 7 ./Projects
	./extract_projects.sh Cli 8 ./Projects
	./extract_projects.sh Cli 9 ./Projects
	./extract_projects.sh Cli 10 ./Projects
	./extract_projects.sh Cli 11 ./Projects
	./extract_projects.sh Cli 12 ./Projects
	./extract_projects.sh Cli 13 ./Projects
	./extract_projects.sh Cli 14 ./Projects
	./extract_projects.sh Cli 15 ./Projects
	./extract_projects.sh Cli 16 ./Projects
	./extract_projects.sh Cli 17 ./Projects
	./extract_projects.sh Cli 18 ./Projects
	./extract_projects.sh Cli 19 ./Projects
	./extract_projects.sh Cli 20 ./Projects
	./extract_projects.sh Cli 21 ./Projects
	./extract_projects.sh Cli 22 ./Projects
	./extract_projects.sh Cli 23 ./Projects
	./extract_projects.sh Cli 24 ./Projects
	./extract_projects.sh Cli 25 ./Projects
	./extract_projects.sh Cli 26 ./Projects
	./extract_projects.sh Cli 27 ./Projects
	./extract_projects.sh Cli 28 ./Projects
	./extract_projects.sh Cli 29 ./Projects
	./extract_projects.sh Cli 30 ./Projects
	./extract_projects.sh Cli 31 ./Projects
	./extract_projects.sh Cli 32 ./Projects
	./extract_projects.sh Cli 33 ./Projects
	./extract_projects.sh Cli 34 ./Projects
	./extract_projects.sh Cli 35 ./Projects
	./extract_projects.sh Cli 36 ./Projects
	./extract_projects.sh Cli 37 ./Projects
	./extract_projects.sh Cli 38 ./Projects
	./extract_projects.sh Cli 39 ./Projects
	./extract_projects.sh Cli 40 ./Projects

fi
if [ "$PROJECT" = "Math" ]; then
	./extract_projects.sh Math 1 ./Projects
	./extract_projects.sh Math 2 ./Projects
	./extract_projects.sh Math 3 ./Projects
	./extract_projects.sh Math 4 ./Projects
	./extract_projects.sh Math 5 ./Projects
	./extract_projects.sh Math 6 ./Projects
	./extract_projects.sh Math 7 ./Projects
	./extract_projects.sh Math 8 ./Projects
	./extract_projects.sh Math 9 ./Projects
	./extract_projects.sh Math 10 ./Projects
	./extract_projects.sh Math 11 ./Projects
	./extract_projects.sh Math 12 ./Projects
	./extract_projects.sh Math 13 ./Projects
	./extract_projects.sh Math 14 ./Projects
	./extract_projects.sh Math 15 ./Projects
	./extract_projects.sh Math 16 ./Projects
	./extract_projects.sh Math 17 ./Projects
	./extract_projects.sh Math 18 ./Projects
	./extract_projects.sh Math 19 ./Projects
	./extract_projects.sh Math 20 ./Projects
	./extract_projects.sh Math 21 ./Projects
	./extract_projects.sh Math 22 ./Projects
	./extract_projects.sh Math 23 ./Projects
	./extract_projects.sh Math 24 ./Projects
	./extract_projects.sh Math 25 ./Projects
	./extract_projects.sh Math 26 ./Projects
	./extract_projects.sh Math 27 ./Projects
	./extract_projects.sh Math 28 ./Projects
	./extract_projects.sh Math 29 ./Projects
	./extract_projects.sh Math 30 ./Projects
	./extract_projects.sh Math 31 ./Projects
	./extract_projects.sh Math 32 ./Projects
	./extract_projects.sh Math 33 ./Projects
	./extract_projects.sh Math 34 ./Projects
	./extract_projects.sh Math 35 ./Projects
	./extract_projects.sh Math 36 ./Projects
	./extract_projects.sh Math 37 ./Projects
	./extract_projects.sh Math 38 ./Projects
	./extract_projects.sh Math 39 ./Projects
	./extract_projects.sh Math 40 ./Projects
	./extract_projects.sh Math 41 ./Projects
	./extract_projects.sh Math 42 ./Projects
	./extract_projects.sh Math 43 ./Projects
	./extract_projects.sh Math 44 ./Projects
	./extract_projects.sh Math 45 ./Projects
	./extract_projects.sh Math 46 ./Projects
	./extract_projects.sh Math 47 ./Projects
	./extract_projects.sh Math 48 ./Projects
	./extract_projects.sh Math 49 ./Projects
	./extract_projects.sh Math 50 ./Projects
	./extract_projects.sh Math 51 ./Projects
	./extract_projects.sh Math 52 ./Projects
	./extract_projects.sh Math 53 ./Projects
	./extract_projects.sh Math 54 ./Projects
	./extract_projects.sh Math 55 ./Projects
	./extract_projects.sh Math 56 ./Projects
	./extract_projects.sh Math 57 ./Projects
	./extract_projects.sh Math 58 ./Projects
	./extract_projects.sh Math 59 ./Projects
	./extract_projects.sh Math 60 ./Projects
	./extract_projects.sh Math 61 ./Projects
	./extract_projects.sh Math 62 ./Projects
	./extract_projects.sh Math 63 ./Projects
	./extract_projects.sh Math 64 ./Projects
	./extract_projects.sh Math 65 ./Projects
	./extract_projects.sh Math 66 ./Projects
	./extract_projects.sh Math 67 ./Projects
	./extract_projects.sh Math 68 ./Projects
	./extract_projects.sh Math 69 ./Projects
	./extract_projects.sh Math 70 ./Projects
	./extract_projects.sh Math 71 ./Projects
	./extract_projects.sh Math 72 ./Projects
	./extract_projects.sh Math 73 ./Projects
	./extract_projects.sh Math 74 ./Projects
	./extract_projects.sh Math 75 ./Projects
	./extract_projects.sh Math 76 ./Projects
	./extract_projects.sh Math 77 ./Projects
	./extract_projects.sh Math 78 ./Projects
	./extract_projects.sh Math 79 ./Projects
	./extract_projects.sh Math 80 ./Projects
	./extract_projects.sh Math 81 ./Projects
	./extract_projects.sh Math 82 ./Projects
	./extract_projects.sh Math 83 ./Projects
	./extract_projects.sh Math 84 ./Projects
	./extract_projects.sh Math 85 ./Projects
	./extract_projects.sh Math 86 ./Projects
	./extract_projects.sh Math 87 ./Projects
	./extract_projects.sh Math 88 ./Projects
	./extract_projects.sh Math 89 ./Projects
	./extract_projects.sh Math 90 ./Projects
	./extract_projects.sh Math 91 ./Projects
	./extract_projects.sh Math 92 ./Projects
	./extract_projects.sh Math 93 ./Projects
	./extract_projects.sh Math 94 ./Projects
	./extract_projects.sh Math 95 ./Projects
	./extract_projects.sh Math 96 ./Projects
	./extract_projects.sh Math 97 ./Projects
	./extract_projects.sh Math 98 ./Projects
	./extract_projects.sh Math 99 ./Projects
	./extract_projects.sh Math 100 ./Projects
	./extract_projects.sh Math 101 ./Projects
	./extract_projects.sh Math 102 ./Projects
	./extract_projects.sh Math 103 ./Projects
	./extract_projects.sh Math 104 ./Projects
	./extract_projects.sh Math 105 ./Projects
	./extract_projects.sh Math 106 ./Projects
fi
