#!/bin/bash
PROJECT=$1

if [ "$PROJECT" = "Chart" ]; then
	./extract_projects.sh Chart 1 ./chart
	./extract_projects.sh Chart 2 ./chart
	./extract_projects.sh Chart 3 ./chart
	./extract_projects.sh Chart 4 ./chart
	./extract_projects.sh Chart 5 ./chart
	./extract_projects.sh Chart 6 ./chart
	./extract_projects.sh Chart 7 ./chart
	./extract_projects.sh Chart 8 ./chart
	./extract_projects.sh Chart 9 ./chart
	./extract_projects.sh Chart 10 ./chart
	./extract_projects.sh Chart 11 ./chart
	./extract_projects.sh Chart 12 ./chart
	./extract_projects.sh Chart 13 ./chart
	./extract_projects.sh Chart 14 ./chart
	./extract_projects.sh Chart 15 ./chart
	./extract_projects.sh Chart 16 ./chart
	./extract_projects.sh Chart 17 ./chart
	./extract_projects.sh Chart 18 ./chart
	./extract_projects.sh Chart 19 ./chart
	./extract_projects.sh Chart 20 ./chart
	./extract_projects.sh Chart 21 ./chart
	./extract_projects.sh Chart 22 ./chart
	./extract_projects.sh Chart 23 ./chart
	./extract_projects.sh Chart 24 ./chart
	./extract_projects.sh Chart 25 ./chart
	./extract_projects.sh Chart 26 ./chart
fi
if [ "$PROJECT" = "Codec" ]; then
	./extract_projects.sh Codec 1 ./codec
	./extract_projects.sh Codec 2 ./codec
	./extract_projects.sh Codec 3 ./codec
	./extract_projects.sh Codec 4 ./codec
	./extract_projects.sh Codec 5 ./codec
	./extract_projects.sh Codec 6 ./codec
	./extract_projects.sh Codec 7 ./codec
	./extract_projects.sh Codec 8 ./codec
	./extract_projects.sh Codec 9 ./codec
	./extract_projects.sh Codec 10 ./codec
	./extract_projects.sh Codec 11 ./codec
	./extract_projects.sh Codec 12 ./codec
	./extract_projects.sh Codec 13 ./codec
	./extract_projects.sh Codec 14 ./codec
	./extract_projects.sh Codec 15 ./codec
	./extract_projects.sh Codec 16 ./codec
	./extract_projects.sh Codec 17 ./codec
	./extract_projects.sh Codec 18 ./codec
fi
if [ "$PROJECT" = "Collections" ]; then
	./extract_projects.sh Collections 25 ./collections
	./extract_projects.sh Collections 26 ./collections
	./extract_projects.sh Collections 27 ./collections
	./extract_projects.sh Collections 28 ./collections
fi
if [ "$PROJECT" = "Compress" ]; then
	./extract_projects.sh Compress 1 ./compress
	./extract_projects.sh Compress 2 ./compress
	./extract_projects.sh Compress 3 ./compress
	./extract_projects.sh Compress 4 ./compress
	./extract_projects.sh Compress 5 ./compress
	./extract_projects.sh Compress 6 ./compress
	./extract_projects.sh Compress 7 ./compress
	./extract_projects.sh Compress 8 ./compress
	./extract_projects.sh Compress 9 ./compress
	./extract_projects.sh Compress 10 ./compress
	./extract_projects.sh Compress 11 ./compress
	./extract_projects.sh Compress 12 ./compress
	./extract_projects.sh Compress 13 ./compress
	./extract_projects.sh Compress 14 ./compress
	./extract_projects.sh Compress 15 ./compress
	./extract_projects.sh Compress 16 ./compress
	./extract_projects.sh Compress 17 ./compress
	./extract_projects.sh Compress 18 ./compress
	./extract_projects.sh Compress 19 ./compress
	./extract_projects.sh Compress 20 ./compress
	./extract_projects.sh Compress 21 ./compress
	./extract_projects.sh Compress 22 ./compress
	./extract_projects.sh Compress 23 ./compress
	./extract_projects.sh Compress 24 ./compress
	./extract_projects.sh Compress 25 ./compress
	./extract_projects.sh Compress 26 ./compress
	./extract_projects.sh Compress 27 ./compress
	./extract_projects.sh Compress 28 ./compress
	./extract_projects.sh Compress 29 ./compress
	./extract_projects.sh Compress 30 ./compress
	./extract_projects.sh Compress 31 ./compress
	./extract_projects.sh Compress 32 ./compress
	./extract_projects.sh Compress 33 ./compress
	./extract_projects.sh Compress 34 ./compress
	./extract_projects.sh Compress 35 ./compress
	./extract_projects.sh Compress 36 ./compress
	./extract_projects.sh Compress 37 ./compress
	./extract_projects.sh Compress 38 ./compress
	./extract_projects.sh Compress 39 ./compress
	./extract_projects.sh Compress 40 ./compress
	./extract_projects.sh Compress 41 ./compress
	./extract_projects.sh Compress 42 ./compress
	./extract_projects.sh Compress 43 ./compress
	./extract_projects.sh Compress 44 ./compress
	./extract_projects.sh Compress 45 ./compress
	./extract_projects.sh Compress 46 ./compress
	./extract_projects.sh Compress 47 ./compress
fi
if [ "$PROJECT" = "Csv" ]; then
	./extract_projects.sh Csv 1 ./csv
	./extract_projects.sh Csv 2 ./csv
	./extract_projects.sh Csv 3 ./csv
	./extract_projects.sh Csv 4 ./csv
	./extract_projects.sh Csv 5 ./csv
	./extract_projects.sh Csv 6 ./csv
	./extract_projects.sh Csv 7 ./csv
	./extract_projects.sh Csv 8 ./csv
	./extract_projects.sh Csv 9 ./csv
	./extract_projects.sh Csv 10 ./csv
	./extract_projects.sh Csv 11 ./csv
	./extract_projects.sh Csv 12 ./csv
	./extract_projects.sh Csv 13 ./csv
	./extract_projects.sh Csv 14 ./csv
	./extract_projects.sh Csv 15 ./csv
	./extract_projects.sh Csv 16 ./csv
fi
if [ "$PROJECT" = "Gson" ]; then
	./extract_projects.sh Gson 1 ./gson
	./extract_projects.sh Gson 2 ./gson
	./extract_projects.sh Gson 3 ./gson
	./extract_projects.sh Gson 4 ./gson
	./extract_projects.sh Gson 5 ./gson
	./extract_projects.sh Gson 6 ./gson
	./extract_projects.sh Gson 7 ./gson
	./extract_projects.sh Gson 8 ./gson
	./extract_projects.sh Gson 9 ./gson
	./extract_projects.sh Gson 10 ./gson
	./extract_projects.sh Gson 11 ./gson
	./extract_projects.sh Gson 12 ./gson
	./extract_projects.sh Gson 13 ./gson
	./extract_projects.sh Gson 14 ./gson
	./extract_projects.sh Gson 15 ./gson
	./extract_projects.sh Gson 16 ./gson
	./extract_projects.sh Gson 17 ./gson
	./extract_projects.sh Gson 18 ./gson
fi
if [ "$PROJECT" = "JacksonCore" ]; then
	./extract_projects.sh JacksonCore 1 ./jacksonCore
	./extract_projects.sh JacksonCore 2 ./jacksonCore
	./extract_projects.sh JacksonCore 3 ./jacksonCore
	./extract_projects.sh JacksonCore 4 ./jacksonCore
	./extract_projects.sh JacksonCore 5 ./jacksonCore
	./extract_projects.sh JacksonCore 6 ./jacksonCore
	./extract_projects.sh JacksonCore 7 ./jacksonCore
	./extract_projects.sh JacksonCore 8 ./jacksonCore
	./extract_projects.sh JacksonCore 9 ./jacksonCore
	./extract_projects.sh JacksonCore 10 ./jacksonCore
	./extract_projects.sh JacksonCore 11 ./jacksonCore
	./extract_projects.sh JacksonCore 12 ./jacksonCore
	./extract_projects.sh JacksonCore 13 ./jacksonCore
	./extract_projects.sh JacksonCore 14 ./jacksonCore
	./extract_projects.sh JacksonCore 15 ./jacksonCore
	./extract_projects.sh JacksonCore 16 ./jacksonCore
	./extract_projects.sh JacksonCore 17 ./jacksonCore
	./extract_projects.sh JacksonCore 18 ./jacksonCore
	./extract_projects.sh JacksonCore 19 ./jacksonCore
	./extract_projects.sh JacksonCore 20 ./jacksonCore
	./extract_projects.sh JacksonCore 21 ./jacksonCore
	./extract_projects.sh JacksonCore 22 ./jacksonCore
	./extract_projects.sh JacksonCore 23 ./jacksonCore
	./extract_projects.sh JacksonCore 24 ./jacksonCore
	./extract_projects.sh JacksonCore 25 ./jacksonCore
	./extract_projects.sh JacksonCore 26 ./jacksonCore
fi
if [ "$PROJECT" = "JacksonXml" ]; then
	./extract_projects.sh JacksonXml 1 ./jacksonXml
	./extract_projects.sh JacksonXml 2 ./jacksonXml
	./extract_projects.sh JacksonXml 3 ./jacksonXml
	./extract_projects.sh JacksonXml 4 ./jacksonXml
	./extract_projects.sh JacksonXml 5 ./jacksonXml
	./extract_projects.sh JacksonXml 6 ./jacksonXml
fi
if [ "$PROJECT" = "Jsoup" ]; then
	./extract_projects.sh Jsoup 1 ./jsoup
	./extract_projects.sh Jsoup 2 ./jsoup
	./extract_projects.sh Jsoup 3 ./jsoup
	./extract_projects.sh Jsoup 4 ./jsoup
	./extract_projects.sh Jsoup 5 ./jsoup
	./extract_projects.sh Jsoup 6 ./jsoup
	./extract_projects.sh Jsoup 7 ./jsoup
	./extract_projects.sh Jsoup 8 ./jsoup
	./extract_projects.sh Jsoup 9 ./jsoup
	./extract_projects.sh Jsoup 10 ./jsoup
	./extract_projects.sh Jsoup 11 ./jsoup
	./extract_projects.sh Jsoup 12 ./jsoup
	./extract_projects.sh Jsoup 13 ./jsoup
	./extract_projects.sh Jsoup 14 ./jsoup
	./extract_projects.sh Jsoup 15 ./jsoup
	./extract_projects.sh Jsoup 16 ./jsoup
	./extract_projects.sh Jsoup 17 ./jsoup
	./extract_projects.sh Jsoup 18 ./jsoup
	./extract_projects.sh Jsoup 19 ./jsoup
	./extract_projects.sh Jsoup 20 ./jsoup
	./extract_projects.sh Jsoup 21 ./jsoup
	./extract_projects.sh Jsoup 22 ./jsoup
	./extract_projects.sh Jsoup 23 ./jsoup
	./extract_projects.sh Jsoup 24 ./jsoup
	./extract_projects.sh Jsoup 25 ./jsoup
	./extract_projects.sh Jsoup 26 ./jsoup
	./extract_projects.sh Jsoup 27 ./jsoup
	./extract_projects.sh Jsoup 28 ./jsoup
	./extract_projects.sh Jsoup 29 ./jsoup
	./extract_projects.sh Jsoup 30 ./jsoup
	./extract_projects.sh Jsoup 31 ./jsoup
	./extract_projects.sh Jsoup 32 ./jsoup
	./extract_projects.sh Jsoup 33 ./jsoup
	./extract_projects.sh Jsoup 34 ./jsoup
	./extract_projects.sh Jsoup 35 ./jsoup
	./extract_projects.sh Jsoup 36 ./jsoup
	./extract_projects.sh Jsoup 37 ./jsoup
	./extract_projects.sh Jsoup 38 ./jsoup
	./extract_projects.sh Jsoup 39 ./jsoup
	./extract_projects.sh Jsoup 40 ./jsoup
	./extract_projects.sh Jsoup 41 ./jsoup
	./extract_projects.sh Jsoup 42 ./jsoup
	./extract_projects.sh Jsoup 43 ./jsoup
	./extract_projects.sh Jsoup 44 ./jsoup
	./extract_projects.sh Jsoup 45 ./jsoup
	./extract_projects.sh Jsoup 46 ./jsoup
	./extract_projects.sh Jsoup 47 ./jsoup
	./extract_projects.sh Jsoup 48 ./jsoup
	./extract_projects.sh Jsoup 49 ./jsoup
	./extract_projects.sh Jsoup 50 ./jsoup
	./extract_projects.sh Jsoup 51 ./jsoup
	./extract_projects.sh Jsoup 52 ./jsoup
	./extract_projects.sh Jsoup 53 ./jsoup
	./extract_projects.sh Jsoup 54 ./jsoup
	./extract_projects.sh Jsoup 55 ./jsoup
	./extract_projects.sh Jsoup 56 ./jsoup
	./extract_projects.sh Jsoup 57 ./jsoup
	./extract_projects.sh Jsoup 58 ./jsoup
	./extract_projects.sh Jsoup 59 ./jsoup
	./extract_projects.sh Jsoup 60 ./jsoup
	./extract_projects.sh Jsoup 61 ./jsoup
	./extract_projects.sh Jsoup 62 ./jsoup
	./extract_projects.sh Jsoup 63 ./jsoup
	./extract_projects.sh Jsoup 64 ./jsoup
	./extract_projects.sh Jsoup 65 ./jsoup
	./extract_projects.sh Jsoup 66 ./jsoup
	./extract_projects.sh Jsoup 67 ./jsoup
	./extract_projects.sh Jsoup 68 ./jsoup
	./extract_projects.sh Jsoup 69 ./jsoup
	./extract_projects.sh Jsoup 70 ./jsoup
	./extract_projects.sh Jsoup 71 ./jsoup
	./extract_projects.sh Jsoup 72 ./jsoup
	./extract_projects.sh Jsoup 73 ./jsoup
	./extract_projects.sh Jsoup 74 ./jsoup
	./extract_projects.sh Jsoup 75 ./jsoup
	./extract_projects.sh Jsoup 76 ./jsoup
	./extract_projects.sh Jsoup 77 ./jsoup
	./extract_projects.sh Jsoup 78 ./jsoup
	./extract_projects.sh Jsoup 79 ./jsoup
	./extract_projects.sh Jsoup 80 ./jsoup
	./extract_projects.sh Jsoup 81 ./jsoup
	./extract_projects.sh Jsoup 82 ./jsoup
	./extract_projects.sh Jsoup 83 ./jsoup
	./extract_projects.sh Jsoup 84 ./jsoup
	./extract_projects.sh Jsoup 85 ./jsoup
	./extract_projects.sh Jsoup 86 ./jsoup
	./extract_projects.sh Jsoup 87 ./jsoup
	./extract_projects.sh Jsoup 88 ./jsoup
	./extract_projects.sh Jsoup 89 ./jsoup
	./extract_projects.sh Jsoup 90 ./jsoup
	./extract_projects.sh Jsoup 91 ./jsoup
	./extract_projects.sh Jsoup 92 ./jsoup
	./extract_projects.sh Jsoup 93 ./jsoup
fi
if [ "$PROJECT" = "JxPath" ]; then
	./extract_projects.sh JxPath 1 ./jxPath
	./extract_projects.sh JxPath 2 ./jxPath
	./extract_projects.sh JxPath 3 ./jxPath
	./extract_projects.sh JxPath 4 ./jxPath
	./extract_projects.sh JxPath 5 ./jxPath
	./extract_projects.sh JxPath 6 ./jxPath
	./extract_projects.sh JxPath 7 ./jxPath
	./extract_projects.sh JxPath 8 ./jxPath
	./extract_projects.sh JxPath 9 ./jxPath
	./extract_projects.sh JxPath 10 ./jxPath
	./extract_projects.sh JxPath 11 ./jxPath
	./extract_projects.sh JxPath 12 ./jxPath
	./extract_projects.sh JxPath 13 ./jxPath
	./extract_projects.sh JxPath 14 ./jxPath
	./extract_projects.sh JxPath 15 ./jxPath
	./extract_projects.sh JxPath 16 ./jxPath
	./extract_projects.sh JxPath 17 ./jxPath
	./extract_projects.sh JxPath 18 ./jxPath
	./extract_projects.sh JxPath 19 ./jxPath
	./extract_projects.sh JxPath 20 ./jxPath
	./extract_projects.sh JxPath 21 ./jxPath
	./extract_projects.sh JxPath 22 ./jxPath
fi
if [ "$PROJECT" = "Lang" ]; then
	./extract_projects.sh Lang 1 ./lang
	./extract_projects.sh Lang 3 ./lang
	./extract_projects.sh Lang 4 ./lang
	./extract_projects.sh Lang 5 ./lang
	./extract_projects.sh Lang 6 ./lang
	./extract_projects.sh Lang 7 ./lang
	./extract_projects.sh Lang 8 ./lang
	./extract_projects.sh Lang 9 ./lang
	./extract_projects.sh Lang 10 ./lang
	./extract_projects.sh Lang 11 ./lang
	./extract_projects.sh Lang 12 ./lang
	./extract_projects.sh Lang 13 ./lang
	./extract_projects.sh Lang 14 ./lang
	./extract_projects.sh Lang 15 ./lang
	./extract_projects.sh Lang 16 ./lang
	./extract_projects.sh Lang 17 ./lang
	./extract_projects.sh Lang 18 ./lang
	./extract_projects.sh Lang 19 ./lang
	./extract_projects.sh Lang 20 ./lang
	./extract_projects.sh Lang 21 ./lang
	./extract_projects.sh Lang 22 ./lang
	./extract_projects.sh Lang 23 ./lang
	./extract_projects.sh Lang 24 ./lang
	./extract_projects.sh Lang 25 ./lang
	./extract_projects.sh Lang 26 ./lang
	./extract_projects.sh Lang 27 ./lang
	./extract_projects.sh Lang 28 ./lang
	./extract_projects.sh Lang 29 ./lang
	./extract_projects.sh Lang 30 ./lang
	./extract_projects.sh Lang 31 ./lang
	./extract_projects.sh Lang 32 ./lang
	./extract_projects.sh Lang 33 ./lang
	./extract_projects.sh Lang 34 ./lang
	./extract_projects.sh Lang 35 ./lang
	./extract_projects.sh Lang 36 ./lang
	./extract_projects.sh Lang 37 ./lang
	./extract_projects.sh Lang 38 ./lang
	./extract_projects.sh Lang 39 ./lang
	./extract_projects.sh Lang 40 ./lang
	./extract_projects.sh Lang 41 ./lang
	./extract_projects.sh Lang 42 ./lang
	./extract_projects.sh Lang 43 ./lang
	./extract_projects.sh Lang 44 ./lang
	./extract_projects.sh Lang 45 ./lang
	./extract_projects.sh Lang 46 ./lang
	./extract_projects.sh Lang 47 ./lang
	./extract_projects.sh Lang 48 ./lang
	./extract_projects.sh Lang 49 ./lang
	./extract_projects.sh Lang 50 ./lang
	./extract_projects.sh Lang 51 ./lang
	./extract_projects.sh Lang 52 ./lang
	./extract_projects.sh Lang 53 ./lang
	./extract_projects.sh Lang 54 ./lang
	./extract_projects.sh Lang 55 ./lang
	./extract_projects.sh Lang 56 ./lang
	./extract_projects.sh Lang 57 ./lang
	./extract_projects.sh Lang 58 ./lang
	./extract_projects.sh Lang 59 ./lang
	./extract_projects.sh Lang 60 ./lang
	./extract_projects.sh Lang 61 ./lang
	./extract_projects.sh Lang 62 ./lang
	./extract_projects.sh Lang 63 ./lang
	./extract_projects.sh Lang 64 ./lang
	./extract_projects.sh Lang 65 ./lang
fi
if [ "$PROJECT" = "Mockito" ]; then
	./extract_projects.sh Mockito 1 ./mockito
	./extract_projects.sh Mockito 2 ./mockito
	./extract_projects.sh Mockito 3 ./mockito
	./extract_projects.sh Mockito 4 ./mockito
	./extract_projects.sh Mockito 5 ./mockito
	./extract_projects.sh Mockito 6 ./mockito
	./extract_projects.sh Mockito 7 ./mockito
	./extract_projects.sh Mockito 8 ./mockito
	./extract_projects.sh Mockito 9 ./mockito
	./extract_projects.sh Mockito 10 ./mockito
	./extract_projects.sh Mockito 11 ./mockito
	./extract_projects.sh Mockito 12 ./mockito
	./extract_projects.sh Mockito 13 ./mockito
	./extract_projects.sh Mockito 14 ./mockito
	./extract_projects.sh Mockito 15 ./mockito
	./extract_projects.sh Mockito 16 ./mockito
	./extract_projects.sh Mockito 17 ./mockito
	./extract_projects.sh Mockito 18 ./mockito
	./extract_projects.sh Mockito 19 ./mockito
	./extract_projects.sh Mockito 20 ./mockito
	./extract_projects.sh Mockito 21 ./mockito
	./extract_projects.sh Mockito 22 ./mockito
	./extract_projects.sh Mockito 23 ./mockito
	./extract_projects.sh Mockito 24 ./mockito
	./extract_projects.sh Mockito 25 ./mockito
	./extract_projects.sh Mockito 26 ./mockito
	./extract_projects.sh Mockito 27 ./mockito
	./extract_projects.sh Mockito 28 ./mockito
	./extract_projects.sh Mockito 29 ./mockito
	./extract_projects.sh Mockito 30 ./mockito
	./extract_projects.sh Mockito 31 ./mockito
	./extract_projects.sh Mockito 32 ./mockito
	./extract_projects.sh Mockito 33 ./mockito
	./extract_projects.sh Mockito 34 ./mockito
	./extract_projects.sh Mockito 35 ./mockito
	./extract_projects.sh Mockito 36 ./mockito
	./extract_projects.sh Mockito 37 ./mockito
	./extract_projects.sh Mockito 38 ./mockito
fi
if [ "$PROJECT" = "Time" ]; then
	./extract_projects.sh Time 1 ./time
	./extract_projects.sh Time 2 ./time
	./extract_projects.sh Time 3 ./time
	./extract_projects.sh Time 4 ./time
	./extract_projects.sh Time 5 ./time
	./extract_projects.sh Time 6 ./time
	./extract_projects.sh Time 7 ./time
	./extract_projects.sh Time 8 ./time
	./extract_projects.sh Time 9 ./time
	./extract_projects.sh Time 10 ./time
	./extract_projects.sh Time 11 ./time
	./extract_projects.sh Time 12 ./time
	./extract_projects.sh Time 13 ./time
	./extract_projects.sh Time 14 ./time
	./extract_projects.sh Time 15 ./time
	./extract_projects.sh Time 16 ./time
	./extract_projects.sh Time 17 ./time
	./extract_projects.sh Time 18 ./time
	./extract_projects.sh Time 19 ./time
	./extract_projects.sh Time 20 ./time
	./extract_projects.sh Time 22 ./time
	./extract_projects.sh Time 23 ./time
	./extract_projects.sh Time 24 ./time
	./extract_projects.sh Time 25 ./time
	./extract_projects.sh Time 26 ./time
	./extract_projects.sh Time 27 ./time
fi
if [ "$PROJECT" = "Cli" ]; then
	./extract_projects.sh Cli 1 ./cli
	./extract_projects.sh Cli 2 ./cli
	./extract_projects.sh Cli 3 ./cli
	./extract_projects.sh Cli 4 ./cli
	./extract_projects.sh Cli 5 ./cli
	./extract_projects.sh Cli 7 ./cli
	./extract_projects.sh Cli 8 ./cli
	./extract_projects.sh Cli 9 ./cli
	./extract_projects.sh Cli 10 ./cli
	./extract_projects.sh Cli 11 ./cli
	./extract_projects.sh Cli 12 ./cli
	./extract_projects.sh Cli 13 ./cli
	./extract_projects.sh Cli 14 ./cli
	./extract_projects.sh Cli 15 ./cli
	./extract_projects.sh Cli 16 ./cli
	./extract_projects.sh Cli 17 ./cli
	./extract_projects.sh Cli 18 ./cli
	./extract_projects.sh Cli 19 ./cli
	./extract_projects.sh Cli 20 ./cli
	./extract_projects.sh Cli 21 ./cli
	./extract_projects.sh Cli 22 ./cli
	./extract_projects.sh Cli 23 ./cli
	./extract_projects.sh Cli 24 ./cli
	./extract_projects.sh Cli 25 ./cli
	./extract_projects.sh Cli 26 ./cli
	./extract_projects.sh Cli 27 ./cli
	./extract_projects.sh Cli 28 ./cli
	./extract_projects.sh Cli 29 ./cli
	./extract_projects.sh Cli 30 ./cli
	./extract_projects.sh Cli 31 ./cli
	./extract_projects.sh Cli 32 ./cli
	./extract_projects.sh Cli 33 ./cli
	./extract_projects.sh Cli 34 ./cli
	./extract_projects.sh Cli 35 ./cli
	./extract_projects.sh Cli 36 ./cli
	./extract_projects.sh Cli 37 ./cli
	./extract_projects.sh Cli 38 ./cli
	./extract_projects.sh Cli 39 ./cli
	./extract_projects.sh Cli 40 ./cli

fi
if [ "$PROJECT" = "Math" ]; then
	./extract_projects.sh Math 1 ./math
	./extract_projects.sh Math 2 ./math
	./extract_projects.sh Math 3 ./math
	./extract_projects.sh Math 4 ./math
	./extract_projects.sh Math 5 ./math
	./extract_projects.sh Math 6 ./math
	./extract_projects.sh Math 7 ./math
	./extract_projects.sh Math 8 ./math
	./extract_projects.sh Math 9 ./math
	./extract_projects.sh Math 10 ./math
	./extract_projects.sh Math 11 ./math
	./extract_projects.sh Math 12 ./math
	./extract_projects.sh Math 13 ./math
	./extract_projects.sh Math 14 ./math
	./extract_projects.sh Math 15 ./math
	./extract_projects.sh Math 16 ./math
	./extract_projects.sh Math 17 ./math
	./extract_projects.sh Math 18 ./math
	./extract_projects.sh Math 19 ./math
	./extract_projects.sh Math 20 ./math
	./extract_projects.sh Math 21 ./math
	./extract_projects.sh Math 22 ./math
	./extract_projects.sh Math 23 ./math
	./extract_projects.sh Math 24 ./math
	./extract_projects.sh Math 25 ./math
	./extract_projects.sh Math 26 ./math
	./extract_projects.sh Math 27 ./math
	./extract_projects.sh Math 28 ./math
	./extract_projects.sh Math 29 ./math
	./extract_projects.sh Math 30 ./math
	./extract_projects.sh Math 31 ./math
	./extract_projects.sh Math 32 ./math
	./extract_projects.sh Math 33 ./math
	./extract_projects.sh Math 34 ./math
	./extract_projects.sh Math 35 ./math
	./extract_projects.sh Math 36 ./math
	./extract_projects.sh Math 37 ./math
	./extract_projects.sh Math 38 ./math
	./extract_projects.sh Math 39 ./math
	./extract_projects.sh Math 40 ./math
	./extract_projects.sh Math 41 ./math
	./extract_projects.sh Math 42 ./math
	./extract_projects.sh Math 43 ./math
	./extract_projects.sh Math 44 ./math
	./extract_projects.sh Math 45 ./math
	./extract_projects.sh Math 46 ./math
	./extract_projects.sh Math 47 ./math
	./extract_projects.sh Math 48 ./math
	./extract_projects.sh Math 49 ./math
	./extract_projects.sh Math 50 ./math
	./extract_projects.sh Math 51 ./math
	./extract_projects.sh Math 52 ./math
	./extract_projects.sh Math 53 ./math
	./extract_projects.sh Math 54 ./math
	./extract_projects.sh Math 55 ./math
	./extract_projects.sh Math 56 ./math
	./extract_projects.sh Math 57 ./math
	./extract_projects.sh Math 58 ./math
	./extract_projects.sh Math 59 ./math
	./extract_projects.sh Math 60 ./math
	./extract_projects.sh Math 61 ./math
	./extract_projects.sh Math 62 ./math
	./extract_projects.sh Math 63 ./math
	./extract_projects.sh Math 64 ./math
	./extract_projects.sh Math 65 ./math
	./extract_projects.sh Math 66 ./math
	./extract_projects.sh Math 67 ./math
	./extract_projects.sh Math 68 ./math
	./extract_projects.sh Math 69 ./math
	./extract_projects.sh Math 70 ./math
	./extract_projects.sh Math 71 ./math
	./extract_projects.sh Math 72 ./math
	./extract_projects.sh Math 73 ./math
	./extract_projects.sh Math 74 ./math
	./extract_projects.sh Math 75 ./math
	./extract_projects.sh Math 76 ./math
	./extract_projects.sh Math 77 ./math
	./extract_projects.sh Math 78 ./math
	./extract_projects.sh Math 79 ./math
	./extract_projects.sh Math 80 ./math
	./extract_projects.sh Math 81 ./math
	./extract_projects.sh Math 82 ./math
	./extract_projects.sh Math 83 ./math
	./extract_projects.sh Math 84 ./math
	./extract_projects.sh Math 85 ./math
	./extract_projects.sh Math 86 ./math
	./extract_projects.sh Math 87 ./math
	./extract_projects.sh Math 88 ./math
	./extract_projects.sh Math 89 ./math
	./extract_projects.sh Math 90 ./math
	./extract_projects.sh Math 91 ./math
	./extract_projects.sh Math 92 ./math
	./extract_projects.sh Math 93 ./math
	./extract_projects.sh Math 94 ./math
	./extract_projects.sh Math 95 ./math
	./extract_projects.sh Math 96 ./math
	./extract_projects.sh Math 97 ./math
	./extract_projects.sh Math 98 ./math
	./extract_projects.sh Math 99 ./math
	./extract_projects.sh Math 100 ./math
	./extract_projects.sh Math 101 ./math
	./extract_projects.sh Math 102 ./math
	./extract_projects.sh Math 103 ./math
	./extract_projects.sh Math 104 ./math
	./extract_projects.sh Math 105 ./math
	./extract_projects.sh Math 106 ./math
fi
